/********************************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

#ifndef SCORE_MW_CRYPTO_API_CERTIFICATE_I_CSR_EXPORT_HPP
#define SCORE_MW_CRYPTO_API_CERTIFICATE_I_CSR_EXPORT_HPP

#include "score/result/result.h"
#include "score/span.hpp"

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string_view>

namespace score
{
namespace mw
{
namespace crypto
{

/// @brief Export interface for a generated Certificate Signing Request.
///
/// Provides access to the DER-encoded CSR data and the submission URL
/// (if configured). The CSR is generated by ICsrGenerationContext::Generate().
class ICsrExport
{
  public:
    using Uptr = std::unique_ptr<ICsrExport>;

    virtual ~ICsrExport() = default;

    ICsrExport(const ICsrExport&) = delete;
    ICsrExport& operator=(const ICsrExport&) = delete;
    ICsrExport(ICsrExport&&) = default;
    ICsrExport& operator=(ICsrExport&&) = default;

    /// @brief Exports the DER-encoded CSR into the provided buffer.
    /// @param output Buffer to receive the encoded CSR
    /// @return Number of bytes written on success
    virtual score::Result<std::size_t> GetEncodedCsr(score::cpp::span<uint8_t> output) const = 0;

    /// @brief Returns the CA submission URL, if configured.
    /// @return URL string or empty string_view if not configured
    virtual std::string_view GetSubmissionUrl() const noexcept = 0;

  protected:
    ICsrExport() = default;
};

}  // namespace crypto
}  // namespace mw
}  // namespace score

#endif  // SCORE_MW_CRYPTO_API_CERTIFICATE_I_CSR_EXPORT_HPP
