/********************************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

#ifndef SCORE_MW_CRYPTO_API_CERTIFICATE_I_OCSP_REQUEST_EXPORT_HPP
#define SCORE_MW_CRYPTO_API_CERTIFICATE_I_OCSP_REQUEST_EXPORT_HPP

#include "score/result/result.h"
#include "score/span.hpp"

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string_view>

namespace score
{
namespace mw
{
namespace crypto
{

/// @brief Export interface for an OCSP request.
///
/// Provides access to the DER-encoded OCSP request data and the
/// OCSP responder URL. Generated by ICertificateManagementContext::GetOcspRequestData().
class IOcspRequestExport
{
  public:
    using Uptr = std::unique_ptr<IOcspRequestExport>;

    virtual ~IOcspRequestExport() = default;

    IOcspRequestExport(const IOcspRequestExport&) = delete;
    IOcspRequestExport& operator=(const IOcspRequestExport&) = delete;
    IOcspRequestExport(IOcspRequestExport&&) = default;
    IOcspRequestExport& operator=(IOcspRequestExport&&) = default;

    /// @brief Exports the DER-encoded OCSP request into the provided buffer.
    /// @param output Buffer to receive the encoded OCSP request
    /// @return Number of bytes written on success
    virtual score::Result<std::size_t> GetEncodedRequest(score::cpp::span<uint8_t> output) const = 0;

    /// @brief Returns the OCSP responder URL.
    /// @return URL string or empty string_view if not configured
    virtual std::string_view GetResponderUrl() const noexcept = 0;

  protected:
    IOcspRequestExport() = default;
};

}  // namespace crypto
}  // namespace mw
}  // namespace score

#endif  // SCORE_MW_CRYPTO_API_CERTIFICATE_I_OCSP_REQUEST_EXPORT_HPP
